plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'maven-publish'
}

group 'SuperiorSkyblock-Missions'

subprojects {
    apply plugin: 'java'
    apply plugin: 'com.github.johnrengelman.shadow'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    repositories {
        maven { url 'https://repo.bg-software.com/repository/nms/' }
        maven { url 'https://repo.bg-software.com/repository/api/' }
        maven { url 'https://repo.bg-software.com/repository/dependencies/' }
        maven { url 'https://repo.bg-software.com/repository/common/' }
        maven { url 'https://repo.papermc.io/repository/maven-public/' }
        maven { url 'https://repo.extendedclip.com/releases/' }
        mavenCentral()
    }

    dependencies {
        compileOnly "io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT"
        compileOnly(files("../SuperiorSkyblock2API.jar"))
    }

    shadowJar {
        archiveFileName = "${project.name}.jar"
        destinationDirectory = file("../target/")
    }

    build {
        dependsOn shadowJar
    }
}

publish.shouldRunAfter shadowJar